name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write
 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.APIKEY }}
      AUTH_DOMAIN: ${{ secrets.AUTHDOMAIN }}
      PROJECT_ID: ${{ secrets.PROJECTID }}
      STORAGE_BUCKET: ${{ secrets.STORAGEBUCKET }}
      MESSAGING_SENDER_ID: ${{ secrets.MESSAGINGSENDERID }}
      APP_ID: ${{ secrets.APPID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace Firebase config placeholders
        run: |
          sed -i.bak "s#__API_KEY__#$API_KEY#g" firebase.js
          sed -i.bak "s#__AUTH_DOMAIN__#$AUTH_DOMAIN#g" firebase.js
          sed -i.bak "s#__PROJECT_ID__#$PROJECT_ID#g" firebase.js
          sed -i.bak "s#__STORAGE_BUCKET__#$STORAGE_BUCKET#g" firebase.js
          sed -i.bak "s#__MESSAGING_SENDER_ID__#$MESSAGING_SENDER_ID#g" firebase.js
          sed -i.bak "s#__APP_ID__#$APP_ID#g" firebase.js

      - name: Verify file content
        run: |
          echo "--- Verifying firebase.js content ---"
          cat firebase.js

      - name: Prepare deployment artifacts
        run: |
          mkdir dist
          cp index.html style.css *.js dist/
          echo "--- Contents of dist directory ---"
          ls -lR dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
